version: '3.8'

services:
  # Servicio de la aplicación (GloveUp API)
  api:
    build: ./server
    container_name: gloveup-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/gloveup
      - PORT=3000
      - ENCRYPTION_KEY=ae157034666ea40cc69f3c3dbcefaf0ca2f22a66d87d980dfff64d72fc3636f5
    depends_on:
      - db

  # Servicio de la Base de Datos (MongoDB)
  db:
    image: mongo:latest
    container_name: gloveup-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Servicio del Frontend (Nginx)
  frontend:
    build: .
    container_name: gloveup-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo_data:
